security:
    encoders:
        UserBundle\Entity\User : bcrypt
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
            entity: { class: UserBundle\Entity\User, property: email }
        #in_memory:
        #    memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            user_checker: app.user_checker
            provider: main
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
                failure_path : login
            logout:
                path: /logout
                target: /
            logout_on_user_change: true
            
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/subscribe, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/admin, roles: ROLE_ADMIN }